[package]
name = "obsidian-graphish"
version = "0.1.0"
edition = "2024"

[dependencies]
# Bindings de Vulkan
ash = "0.38.0" 
# Manejo de ventanas (soporta X11 y Wayland automáticamente)
winit = "0.30.12"
# Necesario para conectar la ventana con la superficie de Vulkan
raw-window-handle = "0.6.2"
# Matemáticas para gráficos
glam = "0.30.9"