[package]
name = "obsidian-graphish"
version = "0.1.0"
edition = "2024"

[dependencies]
# Manejo de ventanas (soporta X11 y Wayland automáticamente)
winit = "0.30.12"
wgpu = "28.0.0"
wasm-bindgen = "0.2.106"
anyhow = "1.0.100"
pollster = "0.4.0"
wasm-bindgen-futures = "0.4.56"
env_logger = "0.11.8"
console_log = "1.0.0"
log = "0.4.29"
bytemuck = "1.20.0"
